# Generated by Django 2.2.16 on 2020-10-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=10)),
                ('userName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('AccBalance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(default=0)),
                ('currentBalance', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('lastFill', models.DateField(verbose_name='Date Issued: ')),
                ('nextMain', models.DateField(verbose_name='Date Issued: ')),
                ('previousBalance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ATM Machine',
            },
        ),
    ]
