# Generated by Django 2.2.16 on 2020-11-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATMCardNumber', models.CharField(max_length=200)),
                ('PIN', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('DOI', models.DateField(verbose_name='Date Issued')),
                ('ExpirationDate', models.DateField()),
                ('Address', models.CharField(max_length=200)),
                ('AccountNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Account')),
            ],
            options={
                'verbose_name': 'ATM Card',
            },
        ),
    ]
