# Generated by Django 2.2.16 on 2020-11-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='ATMCard',
        ),
    ]
