# Generated by Django 2.2.16 on 2020-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201102_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='userActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(default=0)),
            ],
        ),
    ]
