# Generated by Django 2.2.16 on 2020-11-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='minimumBalance',
            field=models.IntegerField(default=0),
        ),
    ]
