# Generated by Django 2.2.16 on 2020-11-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_machine_minimumbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='refillATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refillID', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Machine')),
            ],
            options={
                'verbose_name': 'Refill ATM Machine',
            },
        ),
    ]
