# Generated by Django 2.2.16 on 2020-11-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_refillatm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='previousBalance',
        ),
    ]
