# Generated by Django 2.2.16 on 2020-11-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_machine_previousbalance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machine',
            new_name='ATMMachine',
        ),
    ]
