# Generated by Django 2.2.16 on 2020-11-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201113_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmmachine',
            name='previousBalance',
            field=models.IntegerField(default=0),
        ),
    ]
