# Generated by Django 2.2.16 on 2020-11-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_atmmachine_previousbalance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ATMMachine',
            new_name='Machine',
        ),
    ]
