# Generated by Django 2.2.16 on 2020-11-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201113_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='updatePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNum', models.CharField(max_length=10)),
                ('newNumber', models.IntegerField()),
            ],
        ),
    ]
